### ISSUE TITLE
Which npm & node version to use?

### ISSUE THREAD

**Issue by kermitt2** [Vi-dot/grobid-smecta#1]
Trying to start the angular web app: 

```
lopez@work:~/grobid/grobid-smecta/src/main/webapp/main$ npm start

> grobid-smecta@0.0.1 start /home/lopez/grobid/grobid-smecta/src/main/webapp/main
> ng serve --proxy-config proxy.conf.json --port 5200

/home/lopez/grobid/grobid-smecta/src/main/webapp/main/node_modules/@angular/cli/models/config/config.js:16
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/lopez/grobid/grobid-smecta/src/main/webapp/main/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I am using the latest packaged Ubuntu version of npm (3.10.8) and node (4.6.1), but apparently there is an issue for pre ES2015 syntax.

**Comment by Vi-dot** [comment]
Hello @kermitt2 

I'm using :
node : 7.6.0
npm : 4.1.2

You can use [nvm](https://github.com/creationix/nvm) to easily switch between node versions.

**Comment by kermitt2** [comment]
Apparently ubuntu 16.04 is stuck with node ```4.*```.
Here is the easiest way I found to install node 7.* on Ubuntu Xenial (2 command lines!) :

```bash
$ curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
$ sudo apt-get install -y nodejs
```

```bash
$ node -v
v7.7.2
```
